const all_roles = {
  gk_d: [
    { atr: "Aer", lvl: 2 },
    { atr: "Cmd", lvl: 2 },
    { atr: "Com", lvl: 2 },
    { atr: "Han", lvl: 2 },
    { atr: "Kic", lvl: 2 },
    { atr: "1v1", lvl: 1 },
    { atr: "Ref", lvl: 2 },
    { atr: "Thr", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Agi", lvl: 2 },
  ],
  sk_d: [
    { atr: "Aer", lvl: 1 },
    { atr: "Cmd", lvl: 2 },
    { atr: "Com", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Han", lvl: 1 },
    { atr: "Kic", lvl: 2 },
    { atr: "1v1", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Ref", lvl: 2 },
    { atr: "TRO", lvl: 1 },
    { atr: "Thr", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Agi", lvl: 2 },
  ],
  sk_s: [
    { atr: "Aer", lvl: 1 },
    { atr: "Cmd", lvl: 2 },
    { atr: "Com", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Han", lvl: 1 },
    { atr: "Kic", lvl: 2 },
    { atr: "1v1", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Ref", lvl: 2 },
    { atr: "TRO", lvl: 2 },
    { atr: "Thr", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Agi", lvl: 2 },
  ],
  sk_a: [
    { atr: "Aer", lvl: 1 },
    { atr: "Cmd", lvl: 2 },
    { atr: "Com", lvl: 1 },
    { atr: "Ecc", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Han", lvl: 1 },
    { atr: "Kic", lvl: 2 },
    { atr: "1v1", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Ref", lvl: 2 },
    { atr: "TRO", lvl: 2 },
    { atr: "Thr", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Agi", lvl: 2 },
  ],
  wb_d: [
    { atr: "Cro", lvl: 1 },
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  wb_s: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  wb_a: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 2 },
  ],
  wb_au: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  cwb_s: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  cwb_a: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  fb_d: [
    { atr: "Cro", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  fb_s: [
    { atr: "Cro", lvl: 1 },
    { atr: "Dri", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  fb_a: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  fb_au: [
    { atr: "Cro", lvl: 1 },
    { atr: "Dri", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  iwb_d: [
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  iwb_s: [
    { atr: "Fir", lvl: 2 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  iwb_a: [
    { atr: "Cro", lvl: 1 },
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  iwb_au: [
    { atr: "Fir", lvl: 2 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  ifb_d: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Jum", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  nnfb_d: [
    { atr: "Hea", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  wcb_d: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  wcb_s: [
    { atr: "Cro", lvl: 1 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  wcb_a: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Agi", lvl: 1 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 2 },
  ],
  bpd_d: [
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  bpd_st: [
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Jum", lvl: 2 },
    { atr: "Str", lvl: 2 },
  ],
  bpd_c: [
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Jum", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  cd_d: [
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  cd_st: [
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Jum", lvl: 2 },
    { atr: "Str", lvl: 2 },
  ],
  cd_c: [
    { atr: "Hea", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Jum", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  nncb_d: [
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  nncb_st: [
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Jum", lvl: 2 },
    { atr: "Str", lvl: 2 },
  ],
  nncb_c: [
    { atr: "Hea", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Jum", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  lib_d: [
    { atr: "Fir", lvl: 2 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  lib_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Hea", lvl: 2 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Jum", lvl: 2 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  dlp_d: [
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Bal", lvl: 1 },
  ],
  dlp_s: [
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Bal", lvl: 1 },
  ],
  bwm_d: [
    { atr: "Mar", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 1 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  bwm_s: [
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  sgv_s: [
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Lon", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  sgv_s: [
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Lon", lvl: 2 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  anc_d: [
    { atr: "Mar", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  dm_d: [
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  dm_d: [
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  hb_d: [
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Jum", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  rmp_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  reg_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Bal", lvl: 1 },
  ],
  ap_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Agi", lvl: 1 },
  ],
  ap_a: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Acc", lvl: 1 },
    { atr: "Agi", lvl: 1 },
  ],
  mz_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  mz_a: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  bbm_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  carr_s: [
    { atr: "Fir", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  cm_d: [
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  cm_s: [
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  cm_a: [
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 1 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  cm_au: [
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  am_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Agi", lvl: 1 },
  ],
  am_a: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Agi", lvl: 1 },
  ],
  shw_a: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  engc_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 1 },
    { atr: "Vis", lvl: 2 },
    { atr: "Agi", lvl: 1 },
  ],
  iw_s: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 1 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  iw_a: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 1 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  w_s: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  w_a: [
    { atr: "Cro", lvl: 2 },
    { atr: "Dri", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  wp_s: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Agi", lvl: 1 },
  ],
  wp_a: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
  ],
  dw_d: [
    { atr: "Cro", lvl: 1 },
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Tck", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  dw_s: [
    { atr: "Cro", lvl: 1 },
    { atr: "Dri", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tck", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 1 },
    { atr: "Sta", lvl: 2 },
  ],
  wm_d: [
    { atr: "Cro", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Mar", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Pos", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Sta", lvl: 2 },
  ],
  wm_s: [
    { atr: "Cro", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 2 },
    { atr: "Sta", lvl: 2 },
  ],
  wm_a: [
    { atr: "Cro", lvl: 2 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 1 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 2 },
    { atr: "Sta", lvl: 2 },
  ],
  wm_au: [
    { atr: "Cro", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tck", lvl: 2 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Pos", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 2 },
    { atr: "Sta", lvl: 2 },
  ],
  if_s: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  if_a: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 2 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  rmd_a: [
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Cnt", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 1 },
    { atr: "Bal", lvl: 2 },
    { atr: "Sta", lvl: 1 },
  ],
  trq_a: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Vis", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
  ],
  wtf_s: [
    { atr: "Cro", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Jum", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  wtf_a: [
    { atr: "Cro", lvl: 1 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Wor", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Jum", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  pf_d: [
    { atr: "Fir", lvl: 1 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  pf_s: [
    { atr: "Fir", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  pf_a: [
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Agg", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Cnt", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Wor", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 2 },
    { atr: "Sta", lvl: 2 },
    { atr: "Str", lvl: 1 },
  ],
  p_a: [
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 1 },
    { atr: "Tec", lvl: 1 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Acc", lvl: 1 },
  ],
  af_a: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
  ],
  dlf_s: [
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  dlf_a: [
    { atr: "Dri", lvl: 1 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 2 },
    { atr: "Vis", lvl: 1 },
    { atr: "Bal", lvl: 1 },
    { atr: "Str", lvl: 1 },
  ],
  tf_s: [
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cmp", lvl: 1 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 1 },
    { atr: "Tea", lvl: 2 },
    { atr: "Bal", lvl: 2 },
    { atr: "Jum", lvl: 2 },
    { atr: "Str", lvl: 2 },
  ],
  tf_a: [
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 1 },
    { atr: "Hea", lvl: 2 },
    { atr: "Agg", lvl: 1 },
    { atr: "Ant", lvl: 1 },
    { atr: "Bra", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Bal", lvl: 2 },
    { atr: "Jum", lvl: 2 },
    { atr: "Str", lvl: 2 },
  ],
  f9_s: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 1 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "Fla", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Vis", lvl: 2 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
  ],
  cmp_s: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 1 },
    { atr: "Fir", lvl: 2 },
    { atr: "Hea", lvl: 2 },
    { atr: "Lon", lvl: 2 },
    { atr: "Pas", lvl: 2 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 2 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Vis", lvl: 2 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Jum", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
  cmp_a: [
    { atr: "Dri", lvl: 2 },
    { atr: "Fin", lvl: 2 },
    { atr: "Fir", lvl: 2 },
    { atr: "Hea", lvl: 2 },
    { atr: "Lon", lvl: 1 },
    { atr: "Pas", lvl: 1 },
    { atr: "Tec", lvl: 2 },
    { atr: "Ant", lvl: 2 },
    { atr: "Cmp", lvl: 2 },
    { atr: "Dec", lvl: 1 },
    { atr: "OtB", lvl: 2 },
    { atr: "Tea", lvl: 1 },
    { atr: "Vis", lvl: 1 },
    { atr: "Wor", lvl: 1 },
    { atr: "Acc", lvl: 2 },
    { atr: "Agi", lvl: 2 },
    { atr: "Bal", lvl: 1 },
    { atr: "Jum", lvl: 1 },
    { atr: "Pac", lvl: 1 },
    { atr: "Sta", lvl: 1 },
    { atr: "Str", lvl: 2 },
  ],
};

function getUploadedTableData() {
  const tableData = sessionStorage.getItem("uploadedTableData");
  if (tableData) {
    // Directly return the HTML string
    return tableData;
  } else {
    console.error("No table data found in session storage.");
    return null;
  }
}

const attributeMappings = {
  Cor: "Corners",
  Cro: "Crossing",
  Dri: "Dribbling",
  Fin: "Finishing",
  Fir: "First Touch",
  Fre: "Free Kicks",
  Hea: "Heading",
  Lon: "Long Shots",
  "L Th": "Long Throws",
  Mar: "Marking",
  Pas: "Passing",
  Pen: "Penalties",
  Tck: "Tackling",
  Tec: "Technique",
  Agg: "Aggression",
  Ant: "Anticipation",
  Bra: "Bravery",
  Cmp: "Composure",
  Cnt: "Concentration",
  Dec: "Decisions",
  Det: "Determination",
  Fla: "Flair",
  Ldr: "Leadership",
  OtB: "Off the Ball",
  Pos: "Positioning",
  Tea: "Teamwork",
  Vis: "Vision",
  Wor: "Work Rate",
  Acc: "Acceleration",
  Agi: "Agility",
  Bal: "Balance",
  Jum: "Jumping Reach",
  Nat: "Natural Fitness",
  Pac: "Pace",
  Sta: "Stamina",
  Str: "Strength",
  Aer: "Aerial Reach",
  Cmd: "Command of Area",
  Com: "Communication",
  Ecc: "Eccentricity",
  Han: "Handling",
  Kic: "Kicking",
  "1v1": "One on Ones",
  Pun: "Punching",
  Ref: "Reflexes",
  TRO: "Rushing Out (Tendency)",
  Thr: "Throwing",
};
